---
##
#  pcd-apps/backup defaults
#

# Global BACKUP vars (registered in pcd-common/defaults/main.yml)
#   BACKUP_USER
#   BACKUP_USER_HOME
#   BACKUP_RSYNC_INCLUDES_DIR
#   BACKUP_RSYNC_SITES_FILE


backup_mysql_target: "{{ backup_target_dir }}/{{ ansible_hostname }}-mysql"
backup_files_target: "{{ backup_target_dir }}/{{ ansible_hostname }}-files"
backup_sites_target: "{{ backup_target_dir }}/{{ ansible_hostname }}-sites"


#
# schedule backups  (override in inventory)
#

backup_schedule: {
  sites: { state: absent, hour: "0", minute: 0 },
  files: { state: absent, hour: "0", minute: 0 },
  mysql: { state: absent, hour: "0", minute: 0 }
}

# example webserver schedule 
# backup_schedule: {
#   sites: { state: present, hour: "4", minute: 0 },
#   files: { state: absent, hour: "2", minute: 30 },
#   mysql: { state: present, hour: "10,22", minute: 0 }
# }



# enable s3ql cloud backups
# when enabled, will mount backup_target_dir as a remote filesystem
# recommend using {{ system_uuid }} for prefix.
backup_s3ql_enabled: False
backup_s3ql_url: gs://<bucket>/<prefix>

backup_s3ql_username: "{{ private_user_name }}"
backup_s3ql_password: "{{ private_user_pass }}"

backup_s3ql_mount_opts: ""
#backup_s3ql_mount_opts: "--compress none"



backup_binaries: "{{ BACKUP_USER_HOME }}/bin"
backup_target_dir: "{{ BACKUP_USER_HOME }}/cloud"
