---
##
#  pcd-apps/awstats defaults 
#

# Global AWSTATS vars (registered in pcd-common/defaults/main.yml)
#   AWSTATS_SITE_NAME
#   AWSTATS_SITE_PATH
#   AWSTATS_CONF_DIR

AWSTATS_HTPASSWD_USER: "{{ private_user_name }}"
AWSTATS_HTPASSWD_PASS: "{{ private_user_pass }}"

# how often will awstats be updated? defaults to once a day, 4:30am
AWSTATS_CRON_MINUTE: 30
AWSTATS_CRON_HOUR: 4

# Use the PHP based JAWStats Frontend instead of awstats.pl 
#  directly through cgi-bin
AWSTATS_ENABLE_JAWSTATS_FRONTEND: True



# private
#########

awstats_version: 7.3

awstats_app_dir: "{{ AWSTATS_SITE_PATH }}/awstats-{{ awstats_version }}"
awstats_data_dir: "{{ AWSTATS_SITE_PATH }}/data"
awstats_docroot: "{{ AWSTATS_SITE_PATH }}/www"

awstats_htpasswd_file: "{{ AWSTATS_SITE_PATH }}/awstats-htpasswd"

