---
##
#  pcd-apps/awstats defaults 
#


AWSTATS_HTPASSWD_USER: "{{ private_user_name }}"
AWSTATS_HTPASSWD_PASS: "{{ private_user_pass }}"


# how often will awstats be updated? defaults to once a day, 4:30am
AWSTATS_CRON_MINUTE: 30
AWSTATS_CRON_HOUR: 4

# more AWSTATS vars are registered in pcd-common/defaults/main.yml
# ....


# private
#########

awstats_version: 7.3

awstats_app_dir: "{{ AWSTATS_SITE_PATH }}/awstats-{{ awstats_version }}"
awstats_data_dir: "{{ AWSTATS_SITE_PATH }}/data"
awstats_docroot: "{{ AWSTATS_SITE_PATH }}/www"

awstats_htpasswd_file: "{{ AWSTATS_SITE_PATH }}/awstats-htpasswd"

