---
##
#  pcd-common vars
#

# Register paths
################

PCD_APP_ROLES: "{{ inventory_dir }}/../roles/pcd-apps"
PCD_SERVICE_ROLES: "{{ inventory_dir }}/../roles/pcd-services"
PCD_SITE_ROLES: "{{ inventory_dir }}/../roles/pcd-sites"
PCD_SYSTEM_ROLES: "{{ inventory_dir }}/../roles/pcd-systems"

PCD_COMMON_ROLE: "{{ inventory_dir }}/../roles/pcd-common"

PCD_TASKS: "{{ PCD_COMMON_ROLE }}/tasks/shared"

# Register shared tasks
#######################

pcd_task_add_apache_site: "{{ PCD_TASKS }}/add_apache_site.yml"
pcd_task_add_awstats_config: "{{ PCD_TASKS }}/add_awstats_config.yml"
pcd_task_add_s3ql_mount: "{{ PCD_TASKS }}/add_s3ql_mount.yml"
pcd_task_add_user: "{{ PCD_TASKS }}/add_user.yml"

